### ISSUE TITLE
Zip download contains no twrp*.tar, and build instructions are incomplete

### ISSUE THREAD

**Issue by AlainKnaff** [awesometic/android_device_samsung_gts3llte-twrp#1]
The zip download actually contains no twrp image that could be uploaded using odin (twrp*.tar). Build instructions are incomplete and reference tools which are not standard (repo) or not present in the source tree either (envsetup.sh)

Please make this usable for people that are not in the git (or whatever) bubble by making some more explicit build instructions, or better, by including the result in the zip.

Thanks,

**Comment by awesometic** [comment]
Hello,

It needs AOSP source tree by using the command `repo sync`, and this TWRP image uses a minimal-manifest one with only essential codes and tools for building.

You can get all the required files using `repo` command, there will not be more or less than the current one. 😃 
Containing all source codes in the repository is surely not a good idea. It is really huge, and also AOSP uses more than hundreds of repositories for their codes and the `repo` tool downloads the files from each repository referring to the manifest file.

And, you can find the TWRP image in XDA forum: https://forum.xda-developers.com/t/recovery-unofficial-sm-t820-sm-t825-2022-12-11-twrp-3-7-0_9-0-for-galaxy-tab-s3.4303163/page-3#post-88508839

**Comment by AlainKnaff** [comment]
Thanks for your answer. That still doesn't address where the repo command comes from, however in the meantime I found a working binary :-)

**Comment by awesometic** [comment]
Ah I got it,

You're right, there is no information for getting the `repo` binary in my instructions.
Honestly,  I thought that AOSP developers easily have this binary in advance. But yeah it still needs for those who want TWRP only and aren't an AOSP developer.

Anyway, you can download the latest `repo` binary by the following commands.

```
mkdir ~/bin
curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
chmod a+x ~/bin/repo
```

And don't forget to add `~/bin` directory to your `PATH` variable.
